/-
  Generated by Peregrine from λ□ — do not edit.
  Source constant: Peregrine.Tests.CatCryptConst.addc
  Semantics: Rocq PrimInt63 (unsigned, arithmetic mod 2^63), encoded at w = 64
  with each add/sub/mul/shl result masked by 2^63 - 1.
  Precondition: all inputs < 2^63.
-/
import CatCrypt.Crypto.SecureCompilation.ComBuilder

namespace PeregrineGenerated

open CatCrypt.Crypto.SecureCompilation.ComBuilder
open CatCrypt.Crypto.SecureCompilation.VIR.JasminDialect

/-- `addc` : 1 inputs (levels 0-0), 4 bindings, returns level 4. -/
def addc : NamedSSA where
  nInputs := 1
  bindings :=
    [ ⟨.regConst 64 251, []⟩                  -- v1 := 251
    , ⟨.regArith .add 64, [0, 1]⟩             -- v2 := v0 + v1
    , ⟨.regConst 64 9223372036854775807, []⟩  -- v3 := 2^63 - 1 (mask)
    , ⟨.regArith .and 64, [2, 3]⟩             -- v4 := v2 & v3
    ]
  retLevel := 4

end PeregrineGenerated
