/-
  Generated by Peregrine from λ□ — do not edit.
  Source constant: Peregrine.Tests.CatCryptShare.sq2
  Semantics: Rocq PrimInt63 (unsigned, arithmetic mod 2^63), encoded at w = 64
  with each add/sub/mul/shl result masked by 2^63 - 1.
  Precondition: all inputs < 2^63.
-/
import CatCrypt.Crypto.SecureCompilation.ComBuilder

namespace PeregrineGenerated

open CatCrypt.Crypto.SecureCompilation.ComBuilder
open CatCrypt.Crypto.SecureCompilation.VIR.JasminDialect

/-- `sq2` : 2 inputs (levels 0-1), 5 bindings, returns level 6. -/
def sq2 : NamedSSA where
  nInputs := 2
  bindings :=
    [ ⟨.regArith .mul 64, [0, 1]⟩             -- v2 := v0 * v1
    , ⟨.regConst 64 9223372036854775807, []⟩  -- v3 := 2^63 - 1 (mask)
    , ⟨.regArith .and 64, [2, 3]⟩             -- v4 := v2 & v3
    , ⟨.regArith .add 64, [4, 4]⟩             -- v5 := v4 + v4
    , ⟨.regArith .and 64, [5, 3]⟩             -- v6 := v5 & v3
    ]
  retLevel := 6

end PeregrineGenerated
