/-
  Generated by Peregrine from λ□ — do not edit.
  Source constant: Peregrine.Tests.CatCryptAdd.add3
  Semantics: Rocq PrimInt63 (unsigned, arithmetic mod 2^63), encoded at w = 64
  with each add/sub/mul/shl result masked by 2^63 - 1.
  Precondition: all inputs < 2^63.
-/
import CatCrypt.Crypto.SecureCompilation.ComBuilder

namespace PeregrineGenerated

open CatCrypt.Crypto.SecureCompilation.ComBuilder
open CatCrypt.Crypto.SecureCompilation.VIR.JasminDialect

/-- `add3` : 3 inputs (levels 0-2), 5 bindings, returns level 7. -/
def add3 : NamedSSA where
  nInputs := 3
  bindings :=
    [ ⟨.regArith .add 64, [0, 1]⟩             -- v3 := v0 + v1
    , ⟨.regConst 64 9223372036854775807, []⟩  -- v4 := 2^63 - 1 (mask)
    , ⟨.regArith .and 64, [3, 4]⟩             -- v5 := v3 & v4
    , ⟨.regArith .add 64, [5, 2]⟩             -- v6 := v5 + v2
    , ⟨.regArith .and 64, [6, 4]⟩             -- v7 := v6 & v4
    ]
  retLevel := 7

end PeregrineGenerated
