/-
  Generated by Peregrine from λ□ — do not edit.
  Source constant: Peregrine.Tests.CatCryptShift.mix
  Semantics: Rocq PrimInt63 (unsigned, arithmetic mod 2^63), encoded at w = 64
  with each add/sub/mul/shl result masked by 2^63 - 1.
  Precondition: all inputs < 2^63.
-/
import CatCrypt.Crypto.SecureCompilation.ComBuilder

namespace PeregrineGenerated

open CatCrypt.Crypto.SecureCompilation.ComBuilder
open CatCrypt.Crypto.SecureCompilation.VIR.JasminDialect

/-- `mix` : 2 inputs (levels 0-1), 5 bindings, returns level 6. -/
def mix : NamedSSA where
  nInputs := 2
  bindings :=
    [ ⟨.shrImm 64 3, [0]⟩                     -- v2 := v0 >>> 3
    , ⟨.regArith .mul 64, [1, 1]⟩             -- v3 := v1 * v1
    , ⟨.regConst 64 9223372036854775807, []⟩  -- v4 := 2^63 - 1 (mask)
    , ⟨.regArith .and 64, [3, 4]⟩             -- v5 := v3 & v4
    , ⟨.regArith .and 64, [2, 5]⟩             -- v6 := v2 & v5
    ]
  retLevel := 6

end PeregrineGenerated
