From MetaRocq.Utils Require Import bytestring.
From MetaRocq.Utils Require Import MRString.
From Peregrine Require Import CatCryptIR.
From Stdlib Require Import List.
From Stdlib Require Import PeanoNat.
From Stdlib Require Import ZArith.
From Stdlib Require Import NArith.

Import ListNotations.

Local Open Scope bs_scope.

(* ------------------------------------------------------------------ *)
(*  CatCryptIR → Lean 4 source (a [NamedSSA] literal)                  *)
(*                                                                    *)
(*  Output elaborates with [CatCrypt.Crypto.SecureCompilation.        *)
(*  ComBuilder] and [...VIR.JasminDialect] open, which is what the     *)
(*  emitted [open] lines provide.                                      *)
(* ------------------------------------------------------------------ *)

Definition nl : string := String.String "010"%byte String.EmptyString.

Definition concat_with (sep : string) (xs : list string) : string :=
  String.concat sep xs.

Fixpoint spaces (n : nat) : string :=
  match n with
  | O => ""
  | S k => " " ++ spaces k
  end.

Definition pad_to (w : nat) (s : string) : string :=
  s ++ spaces (w - String.length s).

Definition string_of_N (n : N) : string := string_of_Z (Z.of_N n).

Definition level_name (l : nat) : string := "v" ++ string_of_nat l.

(* ----- Operations -------------------------------------------------- *)

Definition print_binop (b : cc_binop) : string :=
  match b with
  | CCAdd => ".add"
  | CCSub => ".sub"
  | CCMul => ".mul"
  | CCAnd => ".and"
  | CCOr  => ".or"
  | CCXor => ".xor"
  end.

Definition binop_symbol (b : cc_binop) : string :=
  match b with
  | CCAdd => "+"
  | CCSub => "-"
  | CCMul => "*"
  | CCAnd => "&"
  | CCOr  => "|"
  | CCXor => "^"
  end.

Definition print_op (o : cc_op) : string :=
  match o with
  | CCArith b  => ".regArith " ++ print_binop b ++ " 64"
  | CCMulHi    => ".mulhi 64"
  | CCShrImm n => ".shrImm 64 " ++ string_of_nat n
  | CCShlImm n => ".shlImm 64 " ++ string_of_nat n
  | CCConst n  => ".regConst 64 " ++ string_of_N n
  end.

Definition print_binding (b : cc_binding) : string :=
  "⟨" ++ print_op b.(ccb_op) ++ ", ["
      ++ concat_with ", " (List.map string_of_nat b.(ccb_args)) ++ "]⟩".

Definition print_rhs (b : cc_binding) : string :=
  match b.(ccb_op), b.(ccb_args) with
  | CCArith op, [a1; a2] =>
    level_name a1 ++ " " ++ binop_symbol op ++ " " ++ level_name a2
  | CCMulHi, [a1; a2] =>
    "mulhi(" ++ level_name a1 ++ ", " ++ level_name a2 ++ ")"
  | CCShrImm n, [a1] => level_name a1 ++ " >>> " ++ string_of_nat n
  | CCShlImm n, [a1] => level_name a1 ++ " <<< " ++ string_of_nat n
  | CCConst n, _ =>
    if N.eqb n cc_mask63 then "2^63 - 1 (mask)" else string_of_N n
  | o, args =>
    print_op o ++ " [" ++ concat_with ", " (List.map string_of_nat args) ++ "]"
  end.

Definition print_comment (lvl : nat) (b : cc_binding) : string :=
  "-- " ++ level_name lvl ++ " := " ++ print_rhs b.

(* ----- Binding list ------------------------------------------------ *)

Definition binding_lines (ninputs : nat) (bs : list cc_binding) : list string :=
  let texts := List.map print_binding bs in
  let width := List.fold_left (fun m s => Nat.max m (String.length s)) texts 0 in
  let fix aux (lvl : nat) (bs : list cc_binding) (first : bool) : list string :=
    match bs with
    | [] => ["    ]"]
    | b :: rest =>
      ((if first then "    [ " else "    , ")
        ++ pad_to width (print_binding b) ++ "  " ++ print_comment lvl b)
      :: aux (S lvl) rest false
    end in
  aux ninputs bs true.

Definition print_bindings (p : cc_prog) : string :=
  match p.(ccp_bindings) with
  | [] => "  bindings := []"
  | bs => "  bindings :=" ++ nl
            ++ concat_with nl (binding_lines p.(ccp_ninputs) bs)
  end.

(* ----- Whole file --------------------------------------------------- *)

Definition print_header (mask63 : bool) (p : cc_prog) : string :=
  "/-" ++ nl
  ++ "  Generated by Peregrine from λ□ — do not edit." ++ nl
  ++ "  Source constant: " ++ p.(ccp_comment) ++ nl
  ++ "  Semantics: Rocq PrimInt63 (unsigned, arithmetic mod 2^63), encoded at w = 64" ++ nl
  ++ (if mask63 then
        "  with each add/sub/mul/shl result masked by 2^63 - 1." ++ nl
        ++ "  Precondition: all inputs < 2^63." ++ nl
      else
        "  without masking: results are taken mod 2^64 and differ from PrimInt63" ++ nl
        ++ "  whenever an operation overflows 2^63." ++ nl)
  ++ "-/".

Definition print_imports (scaffold : bool) : string :=
  "import CatCrypt.Crypto.SecureCompilation.ComBuilder"
  ++ (if scaffold then
        nl ++ "import CatCrypt.Crypto.SecureCompilation.ARMBackend.ComToArm"
        ++ nl ++ "import CatCrypt.Crypto.SecureCompilation.ARMBackend.ArmAsmPrinter"
      else "").

Definition print_doc (nm : string) (p : cc_prog) : string :=
  let inputs :=
    match p.(ccp_ninputs) with
    | O => "0 inputs"
    | S k => string_of_nat (S k) ++ " inputs (levels 0-" ++ string_of_nat k ++ ")"
    end in
  "/-- `" ++ nm ++ "` : " ++ inputs ++ ", "
    ++ string_of_nat (List.length p.(ccp_bindings)) ++ " bindings, returns level "
    ++ string_of_nat p.(ccp_ret) ++ ". -/".

Definition print_def (nm : string) (p : cc_prog) : string :=
  print_doc nm p ++ nl
  ++ "def " ++ nm ++ " : NamedSSA where" ++ nl
  ++ "  nInputs := " ++ string_of_nat p.(ccp_ninputs) ++ nl
  ++ print_bindings p ++ nl
  ++ "  retLevel := " ++ string_of_nat p.(ccp_ret).

(* Registers are named after the SSA levels; the demo's [w0..] naming is
   32-bit, so the 64-bit path uses [x0..]. *)
Definition print_scaffold (nm : string) (p : cc_prog) : string :=
  let nregs := p.(ccp_ninputs) + List.length p.(ccp_bindings) in
  "#eval " ++ nm ++ ".eval ["
    ++ concat_with ", " (List.repeat "1" p.(ccp_ninputs)) ++ "]" ++ nl
  ++ nl
  ++ "section Scaffold" ++ nl
  ++ "open CatCrypt.Crypto.SecureCompilation.ScalarLinFront" ++ nl
  ++ "open CatCrypt.Crypto.SecureCompilation.ScalarLinDeBruijn" ++ nl
  ++ "open CatCrypt.Crypto.SecureCompilation.ARMBackend" ++ nl
  ++ "open CatCrypt.Crypto.SecureCompilation.ARMBackend.ComToArm" ++ nl
  ++ nl
  ++ "def " ++ nm ++ "Com := (build " ++ nm ++ ").get (by native_decide)" ++ nl
  ++ "def " ++ nm ++ "Arm : List BInst := lowerBBlock (regToBOp (comToRegProg "
    ++ nm ++ "Com " ++ string_of_nat p.(ccp_ninputs) ++ "))" ++ nl
  ++ "def " ++ nm ++ "Alloc : GpAlloc :=" ++ nl
  ++ "  (List.range " ++ string_of_nat nregs
    ++ ").map (fun i => (""v"" ++ toString i, ""x"" ++ toString i))" ++ nl
  ++ "#eval String.intercalate ""\n"" (renderBBlockBody " ++ nm ++ "Alloc " ++ nm ++ "Arm)" ++ nl
  ++ "end Scaffold".

Definition print_program (namespace def_name : string) (mask63 scaffold : bool)
                         (p : cc_prog) : string :=
  let nm := match def_name with
            | String.EmptyString => p.(ccp_name)
            | _ => def_name
            end in
  print_header mask63 p ++ nl
  ++ print_imports scaffold ++ nl
  ++ nl
  ++ "namespace " ++ namespace ++ nl
  ++ nl
  ++ "open CatCrypt.Crypto.SecureCompilation.ComBuilder" ++ nl
  ++ "open CatCrypt.Crypto.SecureCompilation.VIR.JasminDialect" ++ nl
  ++ nl
  ++ print_def nm p ++ nl
  ++ nl
  ++ (if scaffold then print_scaffold nm p ++ nl ++ nl else "")
  ++ "end " ++ namespace ++ nl.
